- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: ClothingOuterHardsuitWarden
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
      - id: ClothingBackpackElectropack
        amount: 2
      - id: RemoteSignaller
        amount: 2

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
      - id: ClothingBackpackElectropack
        amount: 2
      - id: RemoteSignaller
        amount: 2
      - id: Binoculars

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        prob: 0.8
      - id: WeaponDisabler
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.3
      - id: ClothingHeadHelmetBasic
      - id: ClothingOuterArmorBasic
      - id: ClothingBeltSecurityFilled
      - id: Flash
        prob: 0.5
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetSecurity
      - id: ClothingHandsGlovesColorBlack
      - id: ClothingShoesBootsJack
      - id: WeaponMeleeNeedle
        prob: 0.1
      - id: HoloprojectorSecurity
        prob: 0.6
      - id: BookSpaceLaw
        prob: 0.5

- type: entity
  id: LockerBrigmedicFilled
  suffix: Brigmedic, Filled
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesSecurity
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 2
      - id: ClothingOuterHardsuitBrigmedic
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretBrigmedic
      - id: ClothingOuterCoatAMG
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: ClothingUniformJumpskirtOfLife
        prob: 0.1
      - id: MedkitFilled
      - id: MedkitCombatFilled
        prob: 0.6
      - id: MedkitAdvancedFilled
        prob: 0.4
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.3
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitBurnFilled
        prob: 0.7
      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
        prob: 0.15

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesNoir
      - id: ClothingHeadHatDetGadget
      - id: ClothingNeckTieDet
      - id: ClothingOuterVestDetective
      - id: ClothingOuterCoatDetectiveLoadout
      - id: FlippoEngravedLighter
      - id: FlashlightSeclite
      - id: ForensicScanner
      - id: LogProbeCartridge
      - id: BoxForensicPad
      - id: DrinkDetFlask
      - id: ClothingHandsGlovesForensic
      - id: RubberStampDetective
      - id: HoloprojectorSecurity
      - id: BoxEvidenceMarkers
      - id: HandLabeler

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      - id: Wirecutter
      - id: Screwdriver
      - id: Multitool
        prob: 0.5

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponDisabler
      amount: 6

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafePistolMk58
  name: mk58 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolMk58
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entityTable
  id: BaseFillRifleLecter
  table: !type:AllSelector
    children:
    - !type:NestedSelector
      tableId: FillRifleLecterLowPop
      conditions:
      - !type:PlayerCountCondition
        max: 30
    - !type:NestedSelector
      tableId: FillRifleLecterMidPop
      conditions:
      - !type:PlayerCountCondition
        min: 31
        max: 50
    - !type:NestedSelector
      tableId: FillRifleLecterHighPop
      conditions:
      - !type:PlayerCountCondition
        min: 51
        max: 75
    - !type:NestedSelector
      tableId: FillRifleLecterMaxPop
      conditions:
      - !type:PlayerCountCondition
        min: 76

- type: entityTable
  id: FillRifleLecterLowPop
  table: !type:AllSelector
    children:
    - id: WeaponRifleLecter
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entityTable
  id: FillRifleLecterMidPop
  table: !type:AllSelector
    children:
    - id: WeaponRifleLecter
      amount: 3
    - id: MagazineRifle
      amount: 6

- type: entityTable
  id: FillRifleLecterHighPop
  table: !type:AllSelector
    children:
    - id: WeaponRifleLecter
      amount: 4
    - id: MagazineRifle
      amount: 8

- type: entityTable
  id: FillRifleLecterMaxPop
  table: !type:AllSelector
    children:
    - id: WeaponRifleLecter
      amount: 5
    - id: MagazineRifle
      amount: 10

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeRifleLecter
  name: lecter safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: BaseFillRifleLecter

- type: entityTable
  id: BaseFillSubMachineGunDrozd
  table: !type:AllSelector
    children:
    - !type:NestedSelector
      tableId: FillSubMachineGunDrozdLowPop
      conditions:
      - !type:PlayerCountCondition
        max: 30
    - !type:NestedSelector
      tableId: FillSubMachineGunDrozdMidPop
      conditions:
      - !type:PlayerCountCondition
        min: 31
        max: 50
    - !type:NestedSelector
      tableId: FillSubMachineGunDrozdHighPop
      conditions:
      - !type:PlayerCountCondition
        min: 51
        max: 75
    - !type:NestedSelector
      tableId: FillSubMachineGunDrozdMaxPop
      conditions:
      - !type:PlayerCountCondition
        min: 76

- type: entityTable
  id: FillSubMachineGunDrozdLowPop
  table: !type:AllSelector
    children:
    - id: WeaponSubMachineGunDrozd
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entityTable
  id: FillSubMachineGunDrozdMidPop
  table: !type:AllSelector
    children:
    - id: WeaponSubMachineGunDrozd
      amount: 3
    - id: MagazinePistolSubMachineGun
      amount: 6

- type: entityTable
  id: FillSubMachineGunDrozdHighPop
  table: !type:AllSelector
    children:
    - id: WeaponSubMachineGunDrozd
      amount: 4
    - id: MagazinePistolSubMachineGun
      amount: 8

- type: entityTable
  id: FillSubMachineGunDrozdMaxPop
  table: !type:AllSelector
    children:
    - id: WeaponSubMachineGunDrozd
      amount: 5
    - id: MagazinePistolSubMachineGun
      amount: 10

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeSubMachineGunDrozd
  name: drozd safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: BaseFillSubMachineGunDrozd

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeShotgunEnforcer
  name: enforcer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunEnforcer
      amount: 2
    - id: BoxLethalshot
      amount: 4

- type: entityTable
  id: BaseFillShotgunKammerer
  table: !type:AllSelector
    children:
    - !type:NestedSelector
      tableId: FillShotgunKammererLowPop
      conditions:
      - !type:PlayerCountCondition
        max: 30
    - !type:NestedSelector
      tableId: FillShotgunKammererMidPop
      conditions:
      - !type:PlayerCountCondition
        min: 31
        max: 50
    - !type:NestedSelector
      tableId: FillShotgunKammererHighPop
      conditions:
      - !type:PlayerCountCondition
        min: 51
        max: 75
    - !type:NestedSelector
      tableId: FillShotgunKammererMaxPop
      conditions:
      - !type:PlayerCountCondition
        min: 76

- type: entityTable
  id: FillShotgunKammererLowPop
  table: !type:AllSelector
    children:
    - id: WeaponShotgunKammerer
      amount: 2
    - id: BoxLethalshot
      amount: 4

- type: entityTable
  id: FillShotgunKammererMidPop
  table: !type:AllSelector
    children:
    - id: WeaponShotgunKammerer
      amount: 3
    - id: BoxLethalshot
      amount: 6

- type: entityTable
  id: FillShotgunKammererHighPop
  table: !type:AllSelector
    children:
    - id: WeaponShotgunKammerer
      amount: 4
    - id: BoxLethalshot
      amount: 8

- type: entityTable
  id: FillShotgunKammererMaxPop
  table: !type:AllSelector
    children:
    - id: WeaponShotgunKammerer
      amount: 5
    - id: BoxLethalshot
      amount: 10

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeShotgunKammerer
  name: kammerer safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: BaseFillShotgunKammerer

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  name: wt550 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunWt550
      amount: 2
    - id: MagazinePistolSubMachineGunTopMounted
      amount: 4

- type: entityTable
  id: BaseFillWeaponLaserCarbine
  table: !type:AllSelector
    children:
    - !type:NestedSelector
      tableId: FillWeaponLaserCarbineLowPop
      conditions:
      - !type:PlayerCountCondition
        max: 30
    - !type:NestedSelector
      tableId: FillWeaponLaserCarbineMidPop
      conditions:
      - !type:PlayerCountCondition
        min: 31
        max: 50
    - !type:NestedSelector
      tableId: FillWeaponLaserCarbineHighPop
      conditions:
      - !type:PlayerCountCondition
        min: 51
        max: 75
    - !type:NestedSelector
      tableId: FillWeaponLaserCarbineMaxPop
      conditions:
      - !type:PlayerCountCondition
        min: 76

- type: entityTable
  id: FillWeaponLaserCarbineLowPop
  table: !type:AllSelector
    children:
    - id: WeaponLaserCarbine
      amount: 3

- type: entityTable
  id: FillWeaponLaserCarbineMidPop
  table: !type:AllSelector
    children:
    - id: WeaponLaserCarbine
      amount: 4

- type: entityTable
  id: FillWeaponLaserCarbineHighPop
  table: !type:AllSelector
    children:
    - id: WeaponLaserCarbine
      amount: 5

- type: entityTable
  id: FillWeaponLaserCarbineMaxPop
  table: !type:AllSelector
    children:
    - id: WeaponLaserCarbine
      amount: 6

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: BaseFillWeaponLaserCarbine
